name: new_pro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cupertino_icons:
  get:
  responsive_sizer:
  pin_code_fields:
  google_nav_bar:
  flutter_svg:
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl:
  shimmer:
  cached_network_image:
  shared_preferences:
  internet_connection_checker:
  country_picker:
  flutter_staggered_grid_view:
  csc_picker:
  fluttertoast:
  webview_flutter:

  flutter:
    sdk: flutter
  graphview: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons_png/
    - assets/dummy_img/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700




